# -*- coding: utf-8 -*-
"""app1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IIchdS_DZlfeSihSvPVZedWOW9RB0cEo
"""

import streamlit as st
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.metrics import accuracy_score

st.set_page_config(layout="wide")
st.title("Iris Species Prediction with Decision Tree")

st.write("### 1. Data Loading and Initial Inspection")
df = sns.load_dataset('iris')
st.write("Original Iris Dataset Head:")
st.dataframe(df.head())
st.write(f"Dataset shape: {df.shape}")

st.write("### 2. Data Preprocessing")
st.write("Checking for null values:")
st.code("df.isnull().sum()")
st.dataframe(df.isnull().sum().to_frame('Null Count'))

st.write("Checking for duplicate values:")
st.code("df.duplicated().sum()")
duplicates_before = df.duplicated().sum()
st.write(f"Number of duplicates before dropping: {duplicates_before}")

df = df.drop_duplicates()
st.code("df = df.drop_duplicates()")
duplicates_after = df.duplicated().sum()
st.write(f"Number of duplicates after dropping: {duplicates_after}")
st.write("Dataset Head after dropping duplicates:")
st.dataframe(df.head())
st.write(f"Dataset shape after dropping duplicates: {df.shape}")

st.write("### 3. Feature and Target Split")

ip = df.drop('species', axis=1)
op = df['species']

st.write("Input features (ip) head:")
st.dataframe(ip.head())
st.write("Output target (op) head:")
st.dataframe(op.head())

st.write("### 4. Train-Test Split")
x_train, x_test, y_train, y_test = train_test_split(ip, op, random_state=20)
st.write(f"x_train shape: {x_train.shape}")
st.write(f"x_test shape: {x_test.shape}")
st.write(f"y_train shape: {y_train.shape}")
st.write(f"y_test shape: {y_test.shape}")

st.write("### 5. Initial Decision Tree Model Training and Evaluation")
model_initial = DecisionTreeClassifier(random_state=20)
model_initial.fit(x_train, y_train)
pred_initial = model_initial.predict(x_test)
accuracy_initial = accuracy_score(y_test, pred_initial)
st.write(f"Initial Model Accuracy: {accuracy_initial:.4f}")

st.write("### 6. Cross-Validation Score")
score_cv = cross_val_score(model_initial, ip, op, cv=5)
st.write(f"Cross-validation scores: {score_cv}")
st.write(f"Mean CV accuracy: {score_cv.mean():.4f}")
st.write(f"Standard deviation of CV accuracy: {score_cv.std():.4f}")

st.write("### 7. Hyperparameter Tuning with GridSearchCV")
param = {
    "criterion": ["entropy"],
    "max_depth": [5],
    "min_samples_split": [10],
    "min_samples_leaf": [3],
    "max_leaf_nodes": [15],
    "class_weight": ["balanced"]
}

grid = GridSearchCV(DecisionTreeClassifier(random_state=20), param, verbose=1, cv=5)
grid.fit(x_train, y_train)

st.write("Best parameters found by GridSearchCV:")
st.json(grid.best_params_)
st.write("Best estimator from GridSearchCV:")
st.code(str(grid.best_estimator_))

st.write("### 8. Final Model Training and Evaluation with Best Parameters")
model_final = grid.best_estimator_
model_final.fit(x_train, y_train)
pred_final = model_final.predict(x_test)
accuracy_final = accuracy_score(y_test, pred_final)
st.write(f"Final Model Accuracy with Best Parameters: {accuracy_final:.4f}")

st.write("### 9. Decision Tree Visualization")
st.write("Visualizing the trained Decision Tree:")
fig, ax = plt.subplots(figsize=(12, 12))
plot_tree(model_final, filled=True, feature_names=ip.columns.tolist(), class_names=model_final.classes_.tolist(), ax=ax)
st.pyplot(fig)

st.markdown("--- ")
st.write("### Make a Prediction (Interactive Demo)")
st.write("Adjust the sliders to predict the species of an Iris flower.")


sepal_length = st.slider('Sepal Length (cm)', float(ip['sepal_length'].min()), float(ip['sepal_length'].max()), float(ip['sepal_length'].mean()))
sepal_width = st.slider('Sepal Width (cm)', float(ip['sepal_width'].min()), float(ip['sepal_width'].max()), float(ip['sepal_width'].mean()))
petal_length = st.slider('Petal Length (cm)', float(ip['petal_length'].min()), float(ip['petal_length'].max()), float(ip['petal_length'].mean()))
petal_width = st.slider('Petal Width (cm)', float(ip['petal_width'].min()), float(ip['petal_width'].max()), float(ip['petal_width'].mean()))

input_data = pd.DataFrame([{
    'sepal_length': sepal_length,
    'sepal_width': sepal_width,
    'petal_length': petal_length,
    'petal_width': petal_width
}])

if st.button('Predict Species'):
    prediction = model_final.predict(input_data)
    prediction_proba = model_final.predict_proba(input_data)
    st.success(f"Predicted Species: **{prediction[0]}**")
    st.write("Prediction Probabilities:")
    proba_df = pd.DataFrame(prediction_proba, columns=model_final.classes_)
    st.dataframe(proba_df)