# -*- coding: utf-8 -*-
"""DecisionTree.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-qpDvRLp9Bvi6yIfIPtcf8aNtODhcRge
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn import tree
from sklearn.tree import plot_tree



df=sns.load_dataset('iris')

df.columns

df.isnull().sum()

df.duplicated().sum()

df=df.drop_duplicates()

df.duplicated().sum()

df.head()

ip=df.drop('species',axis=1)
op=df['species']

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(ip,op,random_state=20)

from sklearn import tree
plt.figure(figsize=(10,10))
tree.plot_tree(model,filled=True)
st.pyplot(fig)

from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
model=DecisionTreeClassifier()
model.fit(x_train,y_train)
pred=model.predict(x_test)
print(accuracy_score(y_test,pred))

from sklearn.model_selection import cross_val_score
score=cross_val_score(model,x_train,y_train)
print(score.mean(),score.std())

from sklearn.model_selection import GridSearchCV
param={

    "criterion":["entropy"],
    "max_depth": [5],
    "min_samples_split": [10],
    "min_samples_leaf": [3],
    "max_leaf_nodes": [15],
    "class_weight": ["balanced"]
}
grid=GridSearchCV(model,param,verbose=1)

grid.fit(x_train,y_train)

grid.best_estimator_

model=DecisionTreeClassifier(class_weight='balanced', criterion='entropy',
                       max_depth=5, max_leaf_nodes=15, min_samples_leaf=3,
                       min_samples_split=10)
model.fit(x_train,y_train)
pred=model.predict(x_test)
print(accuracy_score(y_test,pred))
